# Site settings
name: （-1，0）的blog
email: mioly@foxmail.com
author: fuyimin
url: 
resume_site: {{ '/books' | prepend: site.baseurl }}
github: https://github.com/aimiy/
baseurl: ""
description: Always a learner!
meta_description: （-1，0）;个人博客;fuyimin;
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: aimiy
rouge: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : disqus
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : aimiy-github-io
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
